# Node.js

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    
  displayName: 'npm install and start'


- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'test'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sonarqube-integration-test'
    cliProjectName: 'sonarqube-integration-test'
    cliSources: '.'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  